# Generated by Django 3.2.13 on 2022-12-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Customer_Name', models.CharField(max_length=30)),
                ('DATE_OF_VISIT', models.DateField()),
                ('Visit_Type', models.CharField(choices=[('WR', 'WARRENTY'), ('AM', 'AMC'), ('BI', 'BILLABLE'), ('IN', 'INSTALLTION')], max_length=2)),
                ('Customer_City', models.CharField(max_length=30)),
                ('Contact_person', models.CharField(max_length=30)),
                ('FCR_IR_SCR_REPORT_NUMBER', models.IntegerField()),
                ('CALL_RECEIVED_D_T', models.DateField()),
                ('CALL_ATTEND_D_T', models.DateField()),
                ('CALL_COMPLETED_D_T', models.DateField()),
                ('CALL_STATUS', models.CharField(choices=[('CO', 'COMPLETED'), ('UO', 'UNDER OBSERVATION'), ('PE', 'PENDING')], max_length=2)),
                ('MACHINE_TYPE', models.CharField(max_length=30)),
                ('MACHINE_MODEL', models.CharField(max_length=30)),
                ('MACHINE_SERIAL_NUMBER', models.CharField(max_length=30)),
                ('SOLUTION_PROVIDED_TO_CUSTOMER', models.CharField(max_length=30)),
                ('ROOM_TEMPERATURE', models.IntegerField()),
                ('DUST_FREE', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('m', 'Maybe')], max_length=2)),
                ('VOLTAGE_EARTHING', models.CharField(max_length=10)),
                ('LIST_OF_SPARES_USED', models.CharField(max_length=30)),
                ('CUSTOMER_FEEDBACK', models.CharField(max_length=30)),
                ('CUSTOMER_COMMENTS', models.CharField(max_length=30)),
                ('ENGINEER_SIGN_NAME_ON_REPORT', models.BooleanField()),
                ('MACHINE_OPERATOR_NAME_ON_REPORT', models.BooleanField()),
                ('CUSTOMER_SIGN_STAMP_NAME_ON_REPORT', models.BooleanField()),
                ('VISIT_PURPOSE', models.CharField(choices=[('SA', 'Sales'), ('IN', 'Installtion'), ('CS', 'Customer Support'), ('SV', 'Site Visit'), ('PM', 'Preventive Maintenance')], max_length=2)),
                ('LIST_OF_PARTS_REPLACED', models.CharField(max_length=30)),
                ('EXPENSES', models.IntegerField()),
                ('REMARK', models.CharField(max_length=30)),
                ('COMPANY_NAME', models.CharField(max_length=30)),
                ('ADDRESS', models.CharField(max_length=30)),
                ('MOBILE_NUMBER', models.IntegerField()),
                ('REQUIREMENTS', models.CharField(max_length=30)),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('SCREEN_SIZESREQUITMEMT_DETAILS', models.CharField(max_length=30)),
                ('MEETING_DETAILS', models.CharField(max_length=30)),
                ('NEXT_FOLLOW_UP_DATE', models.CharField(max_length=30)),
                ('ORDER_STATUS', models.CharField(max_length=30)),
                ('NAME_OF_THE_ENGINEER_CALL_ATTENDED', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
