# Generated by Django 3.2.13 on 2022-12-23 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('ph_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Date_of_visit', models.DateField()),
                ('Visit_type', models.CharField(choices=[('WARRENTY', 'WARRENTY'), ('AMC', 'AMC'), ('BILLABLE', 'BILLABLE'), ('INSTALLTION', 'INSTALLTION')], max_length=15)),
                ('FCR_IR_SCR_Report_Number', models.IntegerField()),
                ('Call_recived_date_and_time', models.DateField()),
                ('Call_attended_date_and_time', models.DateField()),
                ('Call_completed_date_and_time', models.DateField()),
                ('Machine_type', models.CharField(max_length=30)),
                ('Machine_model', models.CharField(max_length=30)),
                ('Machine_serial_number', models.CharField(max_length=30)),
                ('Solution_provided', models.CharField(max_length=30)),
                ('Room_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('Dust_free', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=5)),
                ('Voltage_earthing', models.CharField(blank=True, max_length=10)),
                ('List_of_spares_used', models.CharField(blank=True, max_length=30)),
                ('Customer_feedback', models.CharField(blank=True, max_length=30)),
                ('Customer_comments', models.CharField(blank=True, max_length=30)),
                ('Engineer_sign_name_on_report', models.BooleanField()),
                ('Machine_operator_name_on_report', models.BooleanField()),
                ('Customer_sign_and_stamp_on_report', models.BooleanField()),
                ('Name_of_the_engineer_call_attended', models.CharField(max_length=30)),
                ('Visit_purpose', models.CharField(choices=[('Sales', 'Sales'), ('Installtion', 'Installtion'), ('Customer Support', 'Customer Support'), ('Site Visit', 'Site Visit'), ('Preventive Maintenance', 'Preventive Maintenance')], max_length=22)),
                ('List_of_parts_replaced', models.CharField(blank=True, max_length=30)),
                ('Expenses', models.IntegerField()),
                ('Remark', models.CharField(max_length=30)),
                ('Requirements', models.CharField(max_length=30)),
                ('Approved_status', models.BooleanField(null=True)),
                ('Expense_category', models.CharField(choices=[('Travel and Accommodation', 'Travel and Accommodation'), ('Parts Replaced', 'Parts Replaced')], max_length=30)),
                ('Company_Name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expense.customer_data')),
            ],
        ),
    ]
