# Generated by Django 3.2.13 on 2022-12-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
