# Generated by Django 3.2.13 on 2022-12-29 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_data_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_data',
            name='Approved_Timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
