# Generated by Django 3.2.13 on 2022-12-21 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_customer_data_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_data',
            old_name='Fcr_ir_scr_report_number',
            new_name='FCR_IR_SCR_Report_Number',
        ),
    ]
