# Generated by Django 3.2.13 on 2022-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_rename_fcr_ir_scr_report_number_expense_data_fcr_ir_scr_report_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_data',
            name='Customer_comments',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='Customer_feedback',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='List_of_parts_replaced',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='List_of_spares_used',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='Room_temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense_data',
            name='Voltage_earthing',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
